# __version__.py
# autogenerated by keats 0.2.24
__version__ = "0.1.1"
__name__ = "primer3plus"
__title__ = "primer3plus"
__authors__ = ["Justin Vrana <justin.vrana@gmail.com>"]
__repo__ = None
__homepage__ = None
__description__ = ""
